import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSideRendering } from '@/lib/getServerSideRendering'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
   await getServerSideRendering()
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
